[package]
name = "snowy_auth_program"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "^1.18.0"
borsh = "^1.5.0"
thiserror = "^1.0"

[features]
no-entrypoint = []
